// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcxZJdkATJxH0kpjHXiOvohguj6dJpsk4',
    appId: '1:960328201040:web:338f88e2438f2e3b2fb255',
    messagingSenderId: '960328201040',
    projectId: 'yeni-anaokulu',
    authDomain: 'yeni-anaokulu.firebaseapp.com',
    storageBucket: 'yeni-anaokulu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsFXFnpyDf85-j4aYX1bKaL1XAl1fhjLs',
    appId: '1:960328201040:android:475a9deeaaec33de2fb255',
    messagingSenderId: '960328201040',
    projectId: 'yeni-anaokulu',
    storageBucket: 'yeni-anaokulu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1gdhc0syPa14gaWs2rIz2bpqbivFsMTc',
    appId: '1:960328201040:ios:a1dd69c563b905a42fb255',
    messagingSenderId: '960328201040',
    projectId: 'yeni-anaokulu',
    storageBucket: 'yeni-anaokulu.firebasestorage.app',
    iosBundleId: 'com.example.yeni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1gdhc0syPa14gaWs2rIz2bpqbivFsMTc',
    appId: '1:960328201040:ios:a1dd69c563b905a42fb255',
    messagingSenderId: '960328201040',
    projectId: 'yeni-anaokulu',
    storageBucket: 'yeni-anaokulu.firebasestorage.app',
    iosBundleId: 'com.example.yeni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcxZJdkATJxH0kpjHXiOvohguj6dJpsk4',
    appId: '1:960328201040:web:38bf37e5093fb4082fb255',
    messagingSenderId: '960328201040',
    projectId: 'yeni-anaokulu',
    authDomain: 'yeni-anaokulu.firebaseapp.com',
    storageBucket: 'yeni-anaokulu.firebasestorage.app',
  );
}
